services:
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - demo

  consumer:
    image: node:20-alpine
    container_name: consumer
    networks:
      - demo
    working_dir: /app
    volumes:
      - ./consumer:/app
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - KAFKA_TOPIC=demo-topic
      - KAFKA_CONSUMER_GROUP=demo-consumer-group

networks:
  demo:
    driver: bridge
